export const divisionDistrictsjson = {
  Dhaka: [
    "Dhaka",
    "Gazipur",
    "Kishoreganj",
    "Manikganj",
    "Munshiganj",
    "Narayanganj",
    "Narsingdi",
    "Tangail",
  ],
  Chattogram: [
    "Chattogram",
    "Cox’s Bazar",
    "Cumilla",
    "Feni",
    "Noakhali",
    "Brahmanbaria",
    "Chandpur",
    "Lakshmipur",
  ],
  Rajshahi: [
    "Rajshahi",
    "Pabna",
    "Bogra",
    "Natore",
    "Naogaon",
    "Joypurhat",
    "Chapainawabganj",
    "Sirajganj",
  ],
  Khulna: [
    "Khulna",
    "Jessore",
    "Satkhira",
    "Bagerhat",
    "Meherpur",
    "Narail",
    "Chuadanga",
    "Magura",
  ],
  Barisal: [
    "Barisal",
    "Patuakhali",
    "Bhola",
    "Pirojpur",
    "Barguna",
    "Jhalokathi",
  ],
  Sylhet: ["Sylhet", "Moulvibazar", "Habiganj", "Sunamganj"],
  Rangpur: [
    "Rangpur",
    "Dinajpur",
    "Thakurgaon",
    "Kurigram",
    "Panchagarh",
    "Lalmonirhat",
    "Nilphamari",
    "Gaibandha",
  ],
  Mymensingh: ["Mymensingh", "Netrokona", "Jamalpur", "Sherpur"],
};
